### ISSUE TITLE
Update to WhatsApp

### ISSUE THREAD

**Issue by adityap** [portapps/whatsapp-portable#37]
Today the WhatsApp portable downloaded an update and failed in install attempt. This has caused the app to stop working. Is anyone else facing the same issue?

**Comment by crti** [comment]
Yes, I faced the "update issue" right some hour ago on the 2.2104.10-28 (2021/02/25) version and was not able to resolve by updating to 2.2114.9-29 (2021/04/27). 
I temporarily installed whatsapp_2.2121.7_portable by portable4pc.com but that version only allows one instance at a time - I often run two WhatsApp Desktop Portable at a time so I would happily switch back to this Package here, which allowed that flawlessly. Thx for the efforts to keep this going. 
BTW: when upgrading does it make any sense to migrate the data folder when online data usage is of no concern?

**Comment by danhaber** [comment]
Yes, same here.  It seems that the "disable update checking" isn't working properly.

Anyway, thanks for  your great portables!

**Comment by crazy-max** [comment]
I will take a look, thanks for your feedback.

**Comment by NoMansJob** [comment]
Thanks for looking at it, super solution for RDS-junkies like we are #portables 🥇

**Comment by crazy-max** [comment]
Should be fixed with latest release: https://portapps.io/app/nextcloud-portable/#download
