### ISSUE TITLE
Javascript Error - Fails to Launch

### ISSUE THREAD

**Issue by ab-cc** [portapps/whatsapp-portable#41]
#### Steps to reproduce this issue

1. Install to a new folder
2. Try to launch whatsapp-portable.exe

#### Expected behaviour

Launches WhatsApp

#### Actual behaviour

Throws a Javascript error and fails to start:

![image](https://user-images.githubusercontent.com/45005187/136702191-ac5576ec-b611-4b22-8cb7-b16b60d7b08b.png)

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : v2.2132.6-31 win64

**Operating system (ex. Windows 10 Pro 64 bits)** : Win11

**Winver screenshot** : 
![image](https://user-images.githubusercontent.com/45005187/136702290-d835a5ca-42d8-4c27-b031-fbbda4ed8a96.png)

### Screenshots

![image](https://user-images.githubusercontent.com/45005187/136702191-ac5576ec-b611-4b22-8cb7-b16b60d7b08b.png)

### Logs
[whatsapp-portable.log](https://github.com/portapps/whatsapp-portable/files/7317706/whatsapp-portable.log)

**Comment by Solofandek** [comment]
I have the same problem !

**Comment by crazy-max** [comment]
Should be fixed with latest release [2.2134.10-32](https://portapps.io/app/whatsapp-portable/#download).

**Comment by Solofandek** [comment]
Here's a temporary fix !

1. Go to the official Whatsapp install folder _`AppData\Local\WhatsApp\app-2.2134.10`_ and copy "resources" folder.

2. Past or replace the resources folder that you copied into the Portable installation _`whatsapp-portable-win64-2.2132.6-31\app\app-2.2132.6`_ 

3. Enjoy !
