### ISSUE TITLE
Refrest to up-to-date base whatsapp

### ISSUE THREAD

**Issue by caspertone2003** [portapps/whatsapp-portable#45]
Could you update the portable to reflect currently available whatsapp base?
As per today seems to be WhatsApp for Windows 2.2202.12.0 (64-bit) 

Even not solving the current bug, users could benefit from not needing an active whatsapp app in the mobile ... (one of last features of Window WA)

TIA

**Comment by crazy-max** [comment]
Needs to fix #42 first.
