### ISSUE TITLE
Version 0.3.5374 has virus Trojan.GenericKD.32637835 accordingly to Bitdefender

### ISSUE THREAD

**Issue by asfernandes** [portapps/whatsapp-portable#6]
Version 0.3.5374 has virus Trojan.GenericKD.32637835 accordingly to Bitdefender.

**Comment by crazy-max** [comment]
@asfernandes Thanks for your report. This has been submitted to BitDefender as a false positive and it should be ok soon. Please read also https://portapps.io/doc/faq/#antivirus-complains-about-the-wrapper
